Project1: main.o VectorList.o    
	g++ main.o VectorList.o  -o Project1

main.o: main.cpp
	g++ -c main.cpp

VectorList.o: ./VectorList/VectorList.cpp ./VectorList/VectorList.h
	g++ -c ./VectorList/VectorList.cpp
clean:
	rm*.o Project1